helpers/urls.py
from django.urls import path
 
from .views import (index_page, all_teachers, manage_teachers, teacher_profile, 
    all_students, manage_students, student_profile, manage_subjects, manage_courses
)

app_name = 'helpers'

urlpatterns = [
    path('', index_page, name='index_page'),
    path('all_teachers', all_teachers, name='all_teachers'),
    path('manage_teachers', manage_teachers, name='manage_teachers'),
    path('teacher_profile', teacher_profile, name='teacher_profile'),

    path('all_students', all_students, name='all_students'),
    path('manage_students', manage_students, name='manage_students'),
    path('student_profile', student_profile, name='student_profile'),

    path('manage_subjects', manage_subjects, name='manage_subjects'),
    path('manage_courses', manage_courses, name='manage_courses'),
    
]

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('add/', include('superadmin.urls', namespace='superadmin')),
    path('', include('helpers.urls', namespace='helpers')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superadmin/urls.py
from django.urls import path
 
from .views import add_teacher, add_course, add_student, add_subject

app_name = 'superadmin'

urlpatterns = [
    path('teacher', add_teacher, name='add_teacher'),
    path('course', add_course, name='add_course'),
    path('student', add_student, name='add_student'),
    path('subject', add_subject, name='add_subject'),
]

helpers/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class SessionYearModel(models.Model):
   session_start_year = models.DateField()
   session_end_year = models.DateField()

   def __str__(self):
       return f"{self.session_start_year} - {self.session_end_year}"


class Course(models.Model):
   name = models.CharField(max_length=255, verbose_name='Course Name', )
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return self.name

from students.models import Profile as StudentProfile
from teachers.models import Profile as TeacherProfile
Students = StudentProfile
Teachers = TeacherProfile


class Subject(models.Model):
   name = models.CharField(max_length=255, verbose_name="Subject Name")
   course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
   teacher_id = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
      return self.name


class Attendance(models.Model):
   subject_id = models.ForeignKey(Subject, on_delete=models.DO_NOTHING)
   attendance_date = models.DateField(auto_now_add=True)
   session_year_id = models.ForeignKey(SessionYearModel, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
      return f"Attendance for {self.subject_id} - Year: {self.session_year_id}"


class AttendanceReport(models.Model):
   status = models.BooleanField(default=False)
   student_id = models.ForeignKey(Students, on_delete=models.DO_NOTHING)
   attendance_id = models.ForeignKey(Attendance, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)


class LeaveReportStudent(models.Model):
   student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
   leave_date = models.CharField(max_length=255)
   leave_message = models.TextField()
   leave_status = models.IntegerField(default=0)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)



class LeaveReportTeacher(models.Model):
   teacher_id = models.ForeignKey(Teachers, on_delete=models.CASCADE)
   leave_date = models.CharField(max_length=255)
   leave_message = models.TextField()
   leave_status = models.BooleanField(default=False)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)


class FeedbackStudent(models.Model):
   student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
   feedback = models.TextField()
   feedback_reply = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)


class FeedbackTeacher(models.Model):
   teacher_id = models.ForeignKey(Teachers, on_delete=models.CASCADE)
   feedback = models.CharField(max_length=255)
   feedback_reply = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)


class NotificationStudent(models.Model):
   student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
   message = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)


class NotificationTeacher(models.Model):
   staff_id = models.ForeignKey(Teachers, on_delete=models.CASCADE)
   message = models.TextField()
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)


class StudentResult(models.Model):
   student_id = models.ForeignKey(Students, on_delete=models.DO_NOTHING)
   subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
   subject_exam_marks = models.FloatField(default=0)
   subject_assignment_marks = models.FloatField(default=0)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now_add=True)

helpers/forms.py
from django import forms

from .models import Course


class AddCourseForm(forms.ModelForm):
   class Meta:
      model = Course
      fields = ['name']
      widgets = {
         'name': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Course Name...',
         })
      }
      

helpers/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

User = get_user_model()

from .forms import AddCourseForm


def index_page(request):
   if request.user.is_authenticated:
      if request.user.is_teacher:
         return HttpResponse("You are a teacher!")
      if request.user.is_student:
         return HttpResponse("You are a student!")
      if request.user.is_superadmin or request.user.is_superuser:
         context = {}
         return render(request, 'superadmin/home.html', context)
   else:
      context = {}
      messages.warning(request, "Note that you are not a logged in user, so some activities might be restricted or not function properly.")
      return render(request, 'superadmin/home.html', context)


def all_teachers(request):
   teachers = User.objects.filter(is_teacher=True).order_by('-date_created')
   return render(request, 'superadmin/all_teachers.html', context={'teachers': teachers})


def manage_teachers(request):
   teachers = User.objects.filter(is_teacher=True).order_by('-date_created')
   return render(request, 'superadmin/manage_teachers.html', context={'teachers': teachers})


def teacher_profile(request):
   # teacher = User.objects.get(id=True)
   context={}
   return render(request, 'superadmin/teacher_profile.html')


def all_students(request):
   students = User.objects.filter(is_student=True).order_by('-date_created')
   return render(request, 'superadmin/all_students.html', context={'students': students})


def manage_students(request):
   students = User.objects.filter(is_student=True).order_by('-date_created')
   return render(request, 'superadmin/manage_students.html', context={'students': students})


def student_profile(request):
   # student = User.objects.get(id=True)
   context={}
   return render(request, 'superadmin/student_profile.html')


from helpers.models import Subject, Course
def manage_subjects(request):
   subjects = Subject.objects.all().order_by('-created_at')
   return render(request, 'superadmin/manage_subjects.html', context={'subjects': subjects})


def manage_courses(request):
   courses = Course.objects.all().order_by('-created_at')
   return render(request, 'superadmin/manage_courses.html', context={'courses': courses})

helpers/templates/add_course.html
{% include 'superadmin/register.html' with user_type='Course' %}

helpers/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Widgets</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
   {% block custom_css %}
   {% endblock custom_css %}
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  {% include 'header.html' %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <div class="container mt-4">
      {% include 'messages.html' %}
    </div>
      {% block content %}
      {% endblock content %}
  
      <a id="back-to-top" href="#" class="btn btn-primary back-to-top" role="button" aria-label="Scroll to top">
         <i class="fas fa-chevron-up"></i>
      </a>
  </div>
<!-- /.content-wrapper -->

  <div>
     {% include 'footer.html' %}
  </div>


</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

{% block custom_js %}
{% endblock custom_js %}
</body>
</html>

helpers/templates/footer.html
<footer class="main-footer">
   <div class="float-right d-none d-sm-block">
     <b>Version</b> 3.0.2
   </div>
   <strong>Copyright &copy; 2015-2021 <a href="#">Sabi Programmers</a>.</strong> All rights
   reserved.
 </footer>

helpers/templates/header.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
   <!-- Left navbar links -->
   <ul class="navbar-nav">
     <li class="nav-item">
       <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
     </li>
     <li class="nav-item d-none d-sm-inline-block">
       <a href="../index3.html" class="nav-link">Home</a>
     </li>
     <li class="nav-item d-none d-sm-inline-block">
       <a href="#" class="nav-link">Contact</a>
     </li>
   </ul>

   <!-- SEARCH FORM -->
   <form class="form-inline ml-3">
     <div class="input-group input-group-sm">
       <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
       <div class="input-group-append">
         <button class="btn btn-navbar" type="submit">
           <i class="fas fa-search"></i>
         </button>
       </div>
     </div>
   </form>

   <!-- Right navbar links -->
   <ul class="navbar-nav ml-auto">
     <!-- Messages Dropdown Menu -->
     <li class="nav-item dropdown">
       <a class="nav-link" data-toggle="dropdown" href="#">
         <i class="far fa-comments"></i>
         <span class="badge badge-danger navbar-badge">3</span>
       </a>
       <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
         <a href="#" class="dropdown-item">
           <!-- Message Start -->
           <div class="media">
             <img src="../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
             <div class="media-body">
               <h3 class="dropdown-item-title">
                 Brad Diesel
                 <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
               </h3>
               <p class="text-sm">Call me whenever you can...</p>
               <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
             </div>
           </div>
           <!-- Message End -->
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item">
           <!-- Message Start -->
           <div class="media">
             <img src="../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
             <div class="media-body">
               <h3 class="dropdown-item-title">
                 John Pierce
                 <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
               </h3>
               <p class="text-sm">I got your message bro</p>
               <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
             </div>
           </div>
           <!-- Message End -->
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item">
           <!-- Message Start -->
           <div class="media">
             <img src="../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
             <div class="media-body">
               <h3 class="dropdown-item-title">
                 Nora Silvester
                 <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
               </h3>
               <p class="text-sm">The subject goes here</p>
               <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
             </div>
           </div>
           <!-- Message End -->
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
       </div>
     </li>
     <!-- Notifications Dropdown Menu -->
     <li class="nav-item dropdown">
       <a class="nav-link" data-toggle="dropdown" href="#">
         <i class="far fa-bell"></i>
         <span class="badge badge-warning navbar-badge">15</span>
       </a>
       <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
         <span class="dropdown-item dropdown-header">15 Notifications</span>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item">
           <i class="fas fa-envelope mr-2"></i> 4 new messages
           <span class="float-right text-muted text-sm">3 mins</span>
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item">
           <i class="fas fa-users mr-2"></i> 8 friend requests
           <span class="float-right text-muted text-sm">12 hours</span>
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item">
           <i class="fas fa-file mr-2"></i> 3 new reports
           <span class="float-right text-muted text-sm">2 days</span>
         </a>
         <div class="dropdown-divider"></div>
         <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
       </div>
     </li>
     <li class="nav-item">
       <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
         <i class="fas fa-th-large"></i>
       </a>
     </li>
   </ul>
 </nav>

helpers/templates/index.html
{% extends 'base.html' %}

{% block content %}

   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Admin Dashboard</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="#">Home</a></li>
             <li class="breadcrumb-item active">Dashboard</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">
     <div class="container-fluid">
       <h5 class="mb-2">Info Box</h5>
       <div class="row">
         <div class="col-md-3 col-sm-6 col-12">
           <div class="info-box">
             <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

             <div class="info-box-content">
               <span class="info-box-text">Messages</span>
               <span class="info-box-number">1,410</span>
             </div>
             <!-- /.info-box-content -->
           </div>
           <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-12">
           <div class="info-box">
             <span class="info-box-icon bg-success"><i class="far fa-flag"></i></span>

             <div class="info-box-content">
               <span class="info-box-text">Bookmarks</span>
               <span class="info-box-number">410</span>
             </div>
             <!-- /.info-box-content -->
           </div>
           <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-12">
           <div class="info-box">
             <span class="info-box-icon bg-warning"><i class="far fa-copy"></i></span>

             <div class="info-box-content">
               <span class="info-box-text">Uploads</span>
               <span class="info-box-number">13,648</span>
             </div>
             <!-- /.info-box-content -->
           </div>
           <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-12">
           <div class="info-box">
             <span class="info-box-icon bg-danger"><i class="far fa-star"></i></span>

             <div class="info-box-content">
               <span class="info-box-text">Likes</span>
               <span class="info-box-number">93,139</span>
             </div>
             <!-- /.info-box-content -->
           </div>
           <!-- /.info-box -->
         </div>
         <!-- /.col -->
       </div>
       <!-- /.row -->

       <!-- =========================================================== -->

       <!-- Small Box (Stat card) -->
       <h5 class="mb-2 mt-4">Small Box</h5>
       <div class="row">
         <div class="col-lg-3 col-6">
           <!-- small card -->
           <div class="small-box bg-info">
             <div class="inner">
               <h3>150</h3>

               <p>New Orders</p>
             </div>
             <div class="icon">
               <i class="fas fa-shopping-cart"></i>
             </div>
             <a href="#" class="small-box-footer">
               More info <i class="fas fa-arrow-circle-right"></i>
             </a>
           </div>
         </div>
         <!-- ./col -->
         <div class="col-lg-3 col-6">
           <!-- small card -->
           <div class="small-box bg-success">
             <div class="inner">
               <h3>53<sup style="font-size: 20px">%</sup></h3>

               <p>Bounce Rate</p>
             </div>
             <div class="icon">
               <i class="ion ion-stats-bars"></i>
             </div>
             <a href="#" class="small-box-footer">
               More info <i class="fas fa-arrow-circle-right"></i>
             </a>
           </div>
         </div>
         <!-- ./col -->
         <div class="col-lg-3 col-6">
           <!-- small card -->
           <div class="small-box bg-warning">
             <div class="inner">
               <h3>44</h3>

               <p>User Registrations</p>
             </div>
             <div class="icon">
               <i class="fas fa-user-plus"></i>
             </div>
             <a href="#" class="small-box-footer">
               More info <i class="fas fa-arrow-circle-right"></i>
             </a>
           </div>
         </div>
         <!-- ./col -->
         <div class="col-lg-3 col-6">
           <!-- small card -->
           <div class="small-box bg-danger">
             <div class="inner">
               <h3>65</h3>

               <p>Unique Visitors</p>
             </div>
             <div class="icon">
               <i class="fas fa-chart-pie"></i>
             </div>
             <a href="#" class="small-box-footer">
               More info <i class="fas fa-arrow-circle-right"></i>
             </a>
           </div>
         </div>
         <!-- ./col -->
       </div>
       <!-- /.row -->
     </div><!-- /.container-fluid -->
   </section>
   <!-- /.content -->


{% endblock content %}

helpers/templates/messages.html
{% if messages %}
    {% for message in messages %}
         {% if message.tags == 'error' %}
         <div class="alert alert-danger alert-dismissible fade show" role="alert">
               {{ message }}.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
           {{ message }}.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

helpers/templates/sidebar.html
 {% load static %}
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
   <!-- Brand Logo -->
   <a href="{% url 'helpers:index_page' %}" class="brand-link">
     <img src="{% static 'dist/img/AdminLTELogo.png' %}"
          alt="AdminLTE Logo"
          class="brand-image img-circle elevation-3"
          style="opacity: .8">
     <span class="brand-text font-weight-light">School Management App</span>
   </a>

   <!-- Sidebar -->
   <div class="sidebar">
     <!-- Sidebar user panel (optional) -->
     <div class="user-panel mt-3 pb-3 mb-3 d-flex">
       <div class="image">
         <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
       </div>
       <div class="info">
         <a href="#" class="d-block">Alexander Pierce</a>
       </div>
     </div>

     <!-- Sidebar Menu -->
     <nav class="mt-2">
       <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
         <!-- Add icons to the links using the .nav-icon class
              with font-awesome or any other icon font library -->
         <li class="nav-item has-treeview">
           <a href="#" class="nav-link">
             <i class="nav-icon fas fa-tachometer-alt"></i>
             <p>
               Dashboard
               <i class="right fas fa-angle-left"></i>
             </p>
           </a>
           <ul class="nav nav-treeview">
             <li class="nav-item">
               <a href="{% url 'helpers:index_page' %}" class="nav-link">
                 <i class="far fa-circle nav-icon"></i>
                 <p>Dashboard v1</p>
               </a>
             </li>
           </ul>
         </li>

         <!-- TEACHERS SIDEBAR SECTION -->
         <li class="nav-item has-treeview">
           <a href="#" class="nav-link">
             <i class="nav-icon fas fa-user-tie"></i>
             <p>
               Teachers
               <i class="right fas fa-angle-left"></i>
             </p>
           </a>
           <ul class="nav nav-treeview">
             <li class="nav-item">
               <a href="{% url 'superadmin:add_teacher' %}" class="nav-link">
                 <i class="fas fa-user-plus"></i>
                 <p>Add Teacher</p>
               </a>
             </li>
             <li class="nav-item">
              <a href="{% url 'helpers:all_teachers' %}" class="nav-link">
                <i class="fas fa-user-plus"></i>
                <p>View All Teachers</p>
              </a>
            </li>
             <li class="nav-item">
               <a href="{% url 'helpers:manage_teachers' %}" class="nav-link">
                 <i class="fas fa-user-plus"></i>
                 <p>Manage Teachers</p>
               </a>
             </li>
           </ul>
         </li>
          <!-- END TEACHERS SIDEBAR SECTION -->

         <!-- STUDENT SIDEBAR SECTION -->
         <li class="nav-item has-treeview">
           <a href="#" class="nav-link">
             <i class="nav-icon fas fa-user-tie"></i>
             <p>
               Student 
                <i class="right fas fa-angle-left"></i> <span class="right badge badge-info">6</span>
             </p>
           </a>
           <ul class="nav nav-treeview">
             <li class="nav-item">
               <a href="{% url 'superadmin:add_student' %}" class="nav-link">
                 <i class="fas fa-user-plus"></i>
                 <p>Add Student</p>
               </a>
               <li class="nav-item">
                <a href="{% url 'helpers:all_students' %}" class="nav-link">
                  <i class="fas fa-user-plus"></i>
                  <p>View All Students</p>
                </a>
              </li>
             </li>
             <li class="nav-item">
              <a href="{% url 'helpers:manage_students' %}" class="nav-link">
                <i class="fas fa-user-plus"></i>
                <p>Manage Students</p>
              </a>
            </li>
           </ul>
         </li>
          <!-- END STUDENT SIDEBAR SECTION -->
         
          <!-- COURSE SIDEBAR SECTION -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-user-tie"></i>
              <p>
                Classes
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'superadmin:add_course' %}" class="nav-link">
                  <i class="fas fa-user-plus"></i>
                  <p>Add Course</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'helpers:manage_courses' %}" class="nav-link">
                  <i class="fas fa-user-plus"></i>
                  <p>Manage Courses</p>
                </a>
              </li>
            </ul>
          </li>
            <!-- END COURSE SIDEBAR SECTION --> 
          
                   <!-- SUBJECT SIDEBAR SECTION -->
         <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-user-tie"></i>
            <p>
              Subjects
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'superadmin:add_subject' %}" class="nav-link">
                <i class="fas fa-user-plus"></i>
                <p>Add Subject</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'helpers:manage_subjects' %}" class="nav-link">
                <i class="fas fa-user-plus"></i>
                <p>Manage Subject</p>
              </a>
            </li>
          </ul>
        </li>
         <!-- END SUBJECT SIDEBAR SECTION -->
         <li class="nav-item">
           <a href="#" class="nav-link active">
             <i class="nav-icon fas fa-th"></i>
             <p>
               View Attendance
               <span class="right badge badge-danger">New</span>
             </p>
           </a>
         </li>
         <li class="nav-header">FEEDBACK</li>
         <li class="nav-item">
          <li class="nav-item">
            <a href="gallery.html" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Student Feedback
              </p>
            </a>
          </li>
         </li>
         <li class="nav-item">
           <a href="gallery.html" class="nav-link">
             <i class="nav-icon far fa-image"></i>
             <p>
               Staff Feedback
             </p>
           </a>
         </li>
         <li class="nav-header">MISCELLANEOUS</li>
         <li class="nav-item">
          <a href="gallery.html" class="nav-link">
            <i class="nav-icon far fa-image"></i>
            <p>
              Gallery
            </p>
          </a>
        </li>
        <a href="calendar.html" class="nav-link">
          <i class="nav-icon far fa-calendar-alt"></i>
          <p>
            Calendar
            <span class="badge badge-info right">2</span>
          </p>
        </a>
         <li class="nav-item">
           <a href="https://adminlte.io/docs/3.0" class="nav-link">
             <i class="nav-icon fas fa-file"></i>
             <p>Documentation</p>
           </a>
         </li>
       </ul>
     </nav>
     <!-- /.sidebar-menu -->
   </div>
   <!-- /.sidebar -->
 </aside>