helpers/urls.py
from django.urls import path
 
from .views import (index_page, all_teachers, manage_teachers, teacher_profile, 
    all_students, manage_students, student_profile, manage_subjects, manage_courses
)

app_name = 'helpers'

urlpatterns = [
    path('', index_page, name='index_page'),
    path('all_teachers', all_teachers, name='all_teachers'),
    path('manage_teachers', manage_teachers, name='manage_teachers'),
    path('teacher_profile', teacher_profile, name='teacher_profile'),

    path('all_students', all_students, name='all_students'),
    path('manage_students', manage_students, name='manage_students'),
    path('student_profile', student_profile, name='student_profile'),

    path('manage_subjects', manage_subjects, name='manage_subjects'),
    path('manage_courses', manage_courses, name='manage_courses'),
    
]

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('add/', include('superadmin.urls', namespace='superadmin')),
    path('', include('helpers.urls', namespace='helpers')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superadmin/urls.py
from django.urls import path
 
from .views import add_teacher, add_course, add_student, add_subject

app_name = 'superadmin'

urlpatterns = [
    path('teacher', add_teacher, name='add_teacher'),
    path('course', add_course, name='add_course'),
    path('student', add_student, name='add_student'),
    path('subject', add_subject, name='add_subject'),
]

superadmin/models.py
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save, post_delete
# from django.contrib.auth.models import Group
from django.dispatch import receiver
from django.db import models

User = get_user_model()

def upload_location(instance, filename, *args, **kwargs):
   file_path = 'profile/superadmin/{user_id}/{filename}'.format(user_id=str(instance.user.id), filename=filename)
   return file_path

class Profile(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='superadmin_profile')
   image = models.ImageField(default='', blank=True, null=True, upload_to=upload_location)
   address = models.CharField(max_length=255, null=True, blank=True)
   phone_number = models.CharField(max_length=25, null=True, blank=True)
   skills = models.TextField(max_length=255, null=True, blank=True)
   about = models.TextField(max_length=255, null=True, blank=True)
   eductation = models.CharField(max_length=255, null=True, blank=True)

   def __str__(self):
      return f"{self.user.username}'s Profile"


def user_profile(sender, instance, created, **kwargs):
    if created:
       if instance.is_superadmin or instance.is_superuser:
          Profile.objects.create(user=instance)
post_save.connect(user_profile, sender=User)

@receiver(post_delete, sender=Profile)
def delete_image(sender, instance, *args, **kwargs):
    instance.image.delete(False)

superadmin/forms.py
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()

from helpers.models import Course, SessionYearModel, Subject
from students.models import Profile as StudentProfile


class AddCourseForm(forms.ModelForm):
   class Meta:
      model = Course
      fields = ['name']
      widgets = {
         'name': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Course Name...',
         })
      }


class AddStudentForm(forms.ModelForm):
   password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}))
   password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password Again'}))

   course_list = []
   courses = Course.objects.all()
   for course in courses:
      small_course = (course.id, course.name)
      course_list.append(small_course)

   session_list = []
   sessions = SessionYearModel.objects.all()
   for session in sessions:
      small_session = (session.id, str(session.session_start_year) + '  <--->  ' + str(session.session_end_year))
      session_list.append(small_session)

   gender_choice = (
      ("Male", "Male"),
      ("Female", "Female")
   )

   course = forms.ChoiceField(label="Course Name", choices=course_list, widget=forms.Select(attrs={"class": "form-control"}))
   gender = forms.ChoiceField(label="Gender", choices=gender_choice, widget=forms.Select(attrs={"class": "form-control"}))
   session_year_id = forms.ChoiceField(label="Session Year", choices=session_list, widget=forms.Select(attrs={"class": "form-control"}))

   class Meta:
      model = User
      fields = ['username', 'email','first_name', 'last_name', 'other_name', 'password1', 'password2']
      widgets = {
         'username': forms.TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Enter Username',
         }),
         'email': forms.EmailInput(attrs={
               'class': 'form-control disabled',
               'placeholder': 'Enter Email',
         }),
         'first_name': forms.TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Enter First Name',
         }),
         'last_name': forms.TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Enter Last Name',
         }),
         'other_name': forms.TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Enter Other Names...',
         }),
      }


   def clean_email(self):
      email = self.cleaned_data.get('email').lower()
      qs = User.objects.filter(email=email)
      if qs.exists():
         raise forms.ValidationError("Email Address already taken!")
      return email
   
   def clean_username(self):
      username = self.cleaned_data.get('username').lower()
      qs = User.objects.filter(username=username)
      if qs.exists():
         raise forms.ValidationError("Username already taken!")
      return username
   
   def clean_password2(self):
      password1 = self.cleaned_data.get('password1')
      password2 = self.cleaned_data.get('password2')

      if password1 and password2 and password1 != password2:
         raise forms.ValidationError("Password fields do not match. Recheck...")
      return password2
   
   def save(self, commit=True):
      user = super(AddStudentForm, self).save(commit=False)
      user.set_password(self.cleaned_data['password1'])

      if commit:
         user.save()
      return user
   



class AddSubjectForm(forms.ModelForm):
   class Meta:
      model = Subject
      fields = ['name']
      widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter subject name',
            })
      }

   course = forms.ModelChoiceField(queryset=Course.objects.all(), label="Course Name", widget=forms.Select(attrs={"class": "form-control"}))
   teacher_id = forms.ModelChoiceField(queryset=User.objects.filter(is_teacher=True), label="Teacher:", widget=forms.Select(attrs={"class": "form-control"}))

superadmin/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

User = get_user_model()

from accounts.forms import UserRegisterForm
from teachers.models import Profile as TeacherProfile
from students.models import Profile as StudentProfile

from .forms import AddCourseForm, AddStudentForm, AddSubjectForm

# def superadmin_home(request):
#    print('USER:', request.user)
#    return HttpResponse("You are now in the superadmin home page")

def add_teacher(request):
   form = UserRegisterForm(request.POST or None)
   if request.method == 'POST':
      print('yyyes')
      if form.is_valid():
         user = form.save(commit=False)
         data = form.cleaned_data

         user.first_name = data.get('first_name')
         user.last_name = data.get('last_name')
         user.other_name = data.get('other_name')
         user.is_teacher = True
         
         user.save()

         # user_profile = TeacherProfile.objects.get(user=user)
         # user_profile.address = 'my address here'
         # user_profile.save()
         full_name = f"{data.get('first_name')} {data.get('last_name')}"

         messages.success(request, f'Teacher "{full_name}" successfully registered.')
         return redirect('helpers:index_page')

   return render(request, 'superadmin/add_teacher.html', context={'form': form})


def add_course(request):
   form = AddCourseForm(request.POST or None)
   if request.method == 'POST':
      if form.is_valid():
         form.save()
         messages.success(request, f'Course successfully created.')
         return redirect('helpers:index_page')
   return render(request, 'add_course.html', context={'form': form})


def add_student(request):
   form = AddStudentForm(request.POST or None)
   from helpers.models import Course, SessionYearModel
   if request.method == 'POST':
      if form.is_valid():
         user = form.save(commit=False)
         data = form.cleaned_data

         user.first_name = data.get('first_name')
         user.last_name = data.get('last_name')
         user.other_name = data.get('other_name')
         user.is_student = True

         user.save()

         course_obj = Course.objects.get(id=data.get('course'))
         student_session = SessionYearModel.objects.get(id=data.get('session_year_id'))

         user_profile = StudentProfile.objects.get(user=user)
         user_profile.gender = form.cleaned_data["gender"]
         user_profile.session_year_id = student_session
         user_profile.course_id = course_obj
         
         user_profile.save()

         messages.success(request, 'Student "' + data.get('first_name') + ' ' + data.get('last_name') + '" added successfully')
         return redirect('helpers:index_page')
   return render(request, 'superadmin/add_student.html', context={'form': form})


def add_subject(request):
   form = AddSubjectForm(request.POST or None)
   from helpers.models import Course, SessionYearModel
   if request.method == 'POST':
      if form.is_valid():
         subject = form.save(commit=False)
         data = form.cleaned_data
         
         subject.course_id = data.get('course')
         subject.teacher_id = data.get('teacher_id')
         subject.save()

         messages.success(request, f'Subject "{subject.name}" added successfully')
         return redirect('helpers:index_page')
   return render(request, 'superadmin/add_subject.html', context={'form': form})

templates/superadmin/add_student.html
{% url 'superadmin:add_student_save' as submit_url %}
{% include 'superadmin/register.html' with user_type='Student' submit_url=submit_url %}

templates/superadmin/add_subject.html
{% url 'superadmin:add_subject' as url %}
{% include 'superadmin/register.html' with user_type='Subject' %}

templates/superadmin/add_teacher.html
{% include 'superadmin/register.html' with user_type='Teacher' %}

templates/superadmin/all_students.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>All Students</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="#">Home</a></li>
             <li class="breadcrumb-item active">all students</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">

     <!-- Default box -->
     <div class="card card-solid">
       <div class="card-body pb-0">
         <div class="row d-flex align-items-stretch">
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                  Juliana
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Ohere Juliana</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> UX / Graphic Artist / Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user2-160x160.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="{% url 'helpers:student_profile' %}" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                 Veronica
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Ohere Veronica</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> Graphic Artist / Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="{% url 'helpers:student_profile' %}" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                 Madudi
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Mmaduka Madudi</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user2-160x160.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="{% url 'helpers:student_profile' %}" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                 Biology Student
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Nicole Pearson</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="{% url 'helpers:student_profile' %}" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                 Digital Strategist
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Nicole Pearson</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="#" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
             <div class="card bg-light">
               <div class="card-header text-muted border-bottom-0">
                 Digital Strategist
               </div>
               <div class="card-body pt-0">
                 <div class="row">
                   <div class="col-7">
                     <h2 class="lead"><b>Nicole Pearson</b></h2>
                     <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                     <ul class="ml-4 mb-0 fa-ul text-muted">
                       <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                     </ul>
                   </div>
                   <div class="col-5 text-center">
                     <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="" class="img-circle img-fluid">
                   </div>
                 </div>
               </div>
               <div class="card-footer">
                 <div class="text-right">
                   <a href="#" class="btn btn-sm bg-teal">
                     <i class="fas fa-comments"></i>
                   </a>
                   <a href="#" class="btn btn-sm btn-primary">
                     <i class="fas fa-user"></i> View Profile
                   </a>
                 </div>
               </div>
             </div>
           </div>
          
         </div>
       </div>
       <!-- /.card-body -->
       <div class="card-footer">
         <nav aria-label="Contacts Page Navigation">
           <ul class="pagination justify-content-center m-0">
             <li class="page-item active"><a class="page-link" href="#">1</a></li>
             <li class="page-item"><a class="page-link" href="#">2</a></li>
             <li class="page-item"><a class="page-link" href="#">3</a></li>
             <li class="page-item"><a class="page-link" href="#">4</a></li>
             <li class="page-item"><a class="page-link" href="#">5</a></li>
             <li class="page-item"><a class="page-link" href="#">6</a></li>
             <li class="page-item"><a class="page-link" href="#">7</a></li>
             <li class="page-item"><a class="page-link" href="#">8</a></li>
           </ul>
         </nav>
       </div>
       <!-- /.card-footer -->
     </div>
     <!-- /.card -->

   </section>
   <!-- /.content -->

{% endblock content %}

templates/superadmin/manage_courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Manage Courses</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="#">Home</a></li>
             <li class="breadcrumb-item active">manage courses</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">
     <div class="row">
       <div class="col-12">
         <div class="card">
           <div class="card-header">
             <h3 class="card-title">All Courses</h3>
           </div>
           <!-- /.card-header -->
           <div class="card-body">
             <table id="example2" class="table table-bordered table-hover">
               <thead>
               <tr>
                  <th>#ID</th>
                  <th>Name</th>
                  <th>Date Created</th>
                  <th>Action</th>
               </tr>
               </thead>
               <tbody>
               {% for course in courses %}
               <tr>
                 <td>{{course.id}}</td>
                 <td>{{course.name}}</td>
                 <td>{{course.created_at}}</td>
                 <td><a href="#"><i class="fa fa-edit"></i> Edit</a></td>
               </tr>
               {% endfor %}
               </tbody>
               <tfoot>
               <tr>
                <th>#ID</th>
                <th>Name</th>
                <th>Date Created</th>
                <th>Action</th>
               </tr>
               </tfoot>
             </table>
           </div>
           <!-- /.card-body -->
         </div>
         <!-- /.card -->
       </div>
       <!-- /.col -->
     </div>
     <!-- /.row -->
   </section>
   <!-- /.content -->

{% endblock content %}

templates/superadmin/manage_students.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Manage Students</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="#">Home</a></li>
             <li class="breadcrumb-item active">manage students</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">
     <div class="row">
       <div class="col-12">
         <div class="card">
           <div class="card-header">
             <h3 class="card-title">All Students</h3>
           </div>
           <!-- /.card-header -->
           <div class="card-body">
             <table id="example2" class="table table-bordered table-hover">
               <thead>
               <tr>
                  <th>#ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Address</th>
                  <th>Phone Number</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Date Joined</th>
                  <th>D.O.B</th>
                  <th>Action</th>
               </tr>
               </thead>
               <tbody>
               {% for student in students %}
               <tr>
                 <td>{{student.id}}</td>
                 <td>{{student.first_name}}</td>
                 <td>{{student.last_name}}</td>
                 <td>{{student.email}}</td>
                 <td>{{student.phone_number}}</td>
                 <td>{{student.address}}</td>
                 <td>{{student.gender}}</td>
                 <td>{{student.date_created}}</td>
                 <td>{{student.date_of_birth}}</td>
                 <td><a href="{% url 'helpers:student_profile' %}"><i class="fa fa-edit"></i> Edit</a></td>
               </tr>
               {% endfor %}
               </tbody>
               <tfoot>
               <tr>
                  <th>#ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Address</th>
                  <th>Phone Number</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Date Joined</th>
                  <th>D.O.B</th>
                  <th>Action</th>
               </tr>
               </tfoot>
             </table>
           </div>
           <!-- /.card-body -->
         </div>
         <!-- /.card -->
       </div>
       <!-- /.col -->
     </div>
     <!-- /.row -->
   </section>
   <!-- /.content -->

{% endblock content %}

templates/superadmin/manage_teachers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <div class="container-fluid">
       <div class="row mb-2">
         <div class="col-sm-6">
           <h1>Manage Teachers</h1>
         </div>
         <div class="col-sm-6">
           <ol class="breadcrumb float-sm-right">
             <li class="breadcrumb-item"><a href="#">Home</a></li>
             <li class="breadcrumb-item active">manage teachers</li>
           </ol>
         </div>
       </div>
     </div><!-- /.container-fluid -->
   </section>

   <!-- Main content -->
   <section class="content">
     <div class="row">
       <div class="col-12">
         <div class="card">
           <div class="card-header">
             <h3 class="card-title">All Teachers</h3>
           </div>
           <!-- /.card-header -->
           <div class="card-body">
             <table id="example2" class="table table-bordered table-hover">
               <thead>
               <tr>
                  <th>#ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Address</th>
                  <th>Phone Number</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Date Joined</th>
                  <th>D.O.B</th>
                  <th>Action</th>
               </tr>
               </thead>
               <tbody>
               {% for teacher in teachers %}
               <tr>
                 <td>{{teacher.id}}</td>
                 <td>{{teacher.first_name}}</td>
                 <td>{{teacher.last_name}}</td>
                 <td>{{teacher.email}}</td>
                 <td>{{teacher.phone_number}}</td>
                 <td>{{teacher.address}}</td>
                 <td>{{teacher.gender}}</td>
                 <td>{{teacher.date_created}}</td>
                 <td>{{teacher.date_of_birth}}</td>
                 <td><a href="{% url 'helpers:teacher_profile' %}"><i class="fa fa-edit"></i> Edit</a></td>
               </tr>
               {% endfor %}
               </tbody>
               <tfoot>
               <tr>
                  <th>#ID</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email Address</th>
                  <th>Phone Number</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Date Joined</th>
                  <th>D.O.B</th>
                  <th>Action</th>
               </tr>
               </tfoot>
             </table>
           </div>
           <!-- /.card-body -->
         </div>
         <!-- /.card -->
       </div>
       <!-- /.col -->
     </div>
     <!-- /.row -->
   </section>
   <!-- /.content -->

{% endblock content %}